<?php
/**
 * Created by PhpStorm.
 * User: linyang
 * Date: 16/10/27
 * Time: 下午6:43
 */

namespace model;


use com\cube\core\Proxy;
use modules\mongo\Mongo;

/**
 * Class MongoProxy.
 * Mongodb test
 * @package model
 */
class MongoProxy extends Proxy
{
    public function __construct()
    {
        parent::__construct();

        Mongo::init([
            'host' => 'localhost',
            'port' => 27017,
            'user' => 'dev',
            'password' => 'your db password',
            'db' => 'system'
        ]);
    }

    public function getName()
    {
        return 'mongo';
    }

    public function execute($value)
    {
//        return parent::execute($value); // TODO: Change the autogenerated stub

        $result = Mongo::model('list')->find();
        $arr = [];
        foreach ($result as $value) {
            array_push($arr, $value);
        }
        return $arr;
    }

    public function onRemove()
    {
        parent::onRemove(); // TODO: Change the autogenerated stub

        Mongo::close();
    }
}

new MongoProxy();