<?php
/**
 * Created by PhpStorm.
 * User: linyang
 * Date: 16/10/2
 * Time: 下午5:27
 */

namespace model;

use com\cube\db\DB;
use com\cube\core\Proxy;

/**
 * Class MysqlProxy.
 * @package model
 */
class MysqlProxy extends Proxy
{
    public function __construct()
    {
        parent::__construct();

        DB::init([
            'host' => 'localhost',
            'port' => 3306,
            'user' => 'root',
            'password' => '',
            'db' => 'system',
            'prefix' => ''
        ]);
    }

    public function getName()
    {
        return 'mysql';
    }

    public function execute($value)
    {
        switch ($value) {
            case 'getUserCount':
                return DB::model('user')->select();
        }
    }

    public function onRemove()
    {
        parent::onRemove(); // TODO: Change the autogenerated stub

        DB::close();
    }
}

new MysqlProxy();