<?php
/**
 * Created by PhpStorm.
 * User: linyang
 * Date: 16/10/28
 * Time: 上午10:23
 */

namespace model;

use modules\redis\Redis;
use com\cube\core\Proxy;

/**
 * Class RedisProxy.
 * RedisStore test.
 * @package model
 */
class RedisProxy extends Proxy
{
    public function __construct()
    {
        parent::__construct();

        Redis::init([
            'host' => 'localhost',
            'port' => 6379,
            'db' => '0',
            'password' => 'db password'
        ]);
    }

    public function getName()
    {
        return 'mongo';
    }

    public function execute($value)
    {
        return Redis::model()->dbsize();
    }

    public function onRemove()
    {
        parent::onRemove(); // TODO: Change the autogenerated stub

        Redis::close();
    }
}

new RedisProxy();